# Generated by Django 4.0.6 on 2022-09-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0002_alter_autor_miembro_es_miembro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor_miembro',
            name='es_miembro',
            field=models.BooleanField(null=True),
        ),
    ]
